# LJ units muVT example with external wall potential (single-component)
experiment:
  # name: "lj_muVT_wall_h_${system.h}"
  name: "KCl_nvt_wall_test"
  results_dir: "results"
  description: "KCl liquid in nvt ensemble"

units:
  system: "standard"

simulation:
  ensemble: "NVT"
  temperature: 1045 # K
  n_steps: 1000

system:
  n_atoms: 256
  initial_capacity: 256
  init:
    # mode: "random"        # options: random, uniform
    # min_distance: 1     # used in random mode
    mode: "uniform"
    # padding: [0.0, 0.0, 0.7]
  box: [10, 10, 10]
  pbc: [true, true, true]

ewald:
  alpha: 0.25
  real_cut: 6.0
  n_c: 4
  dielectric: 1.0
  z_scale_factor: 1.0  # Scale factor for z dimension to avoid periodic interactions
  dipole_correction: false

types:
  K:
    name: "K"
    mass: 39.0983 # amu
    charge: 1.0 # e
    count: 64
  Cl:
    name: "Cl"
    mass: 35.453 # amu
    charge: -1.0 # e
    count: 64

pairs:
  # Pairwise LJ interaction between the single type with standard cutoff
  - types: [K, K]
    forces:
      - {
        kind: huggins_mayer,
        sigma: 0.2926,
        b: 25.474,
        B: 29.7,
        c: -1.463e-3,
        d: -1.445e-5,
        cutoff: 2.5
      }
      - { kind: ewald }
  - types: [Cl, Cl]
    forces:
      - {
        kind: huggins_mayer,
        sigma: 0.3170,
        b: 15.2360,
        B: 29.7,
        c: -7.49757e-3,
        d: -1.50554e-4,
        cutoff: 2.5
      }
      - { kind: ewald }
  - types: [K, Cl]
    forces:
      - {
        kind: huggins_mayer,
        sigma: 0.3048 ,
        b: 20.3549,
        B: 29.7,
        c: -2.89063e-3,
        d: -4.39616e-5,
        cutoff: 2.5
      }
      - { kind: ewald }

sampler:
  actions:
    - action: "translate"
      probability: 1.0
  max_displacement: 0.1

  force_recompute: false

debug: false

logger:
  log_interval: 10
  xyz_interval: 10
