# LJ units muVT example (single-component)
experiment:
  name: "lj_muVT_mu_${simulation.mu}_T_${simulation.temperature}"
  # name: "lj_muVT_test"
  results_dir: "results"
  description: "LJ fluid in muVT ensemble (LJ units)"

debug: false

simulation:
  ensemble: "muVT"
  temperature: 2.0 # 1.2
  mu: -2.477            # LJ chemical potential (example)
  n_steps: 1000

system:
  n_atoms: 512
  initial_capacity: 1024
  init:
    # mode: "random"        # options: random, uniform
    # min_distance: 1     # used in random mode
    mode: "uniform"
  box: [10, 10, 10]
  pbc: [true, true, true]

units:
  system: "lj"

types:
  LJ:
    name: "LJ"
    mass: 1.0
    charge: 0.0
    fraction: 1.0

pairs:
  - types: [LJ, LJ]
    forces:
      - {
        kind: LJ,
        sigma: 1,
        epsilon: 1,
        cutoff: 2.5
      }
sampler:
  actions:
    - action: "translate"
      probability: 0.7
    - action: "insert"
      probability: 0.15
    - action: "delete"
      probability: 0.15
  max_displacement: 0.1
  force_recompute: false

logger:
  log_interval: 10
  xyz_interval: 200
